[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/a1f1bcc826fc4d76bbd0f36a884c4608"

[etherscan]
sepolia = { key = "HUQIWURC19G3G1171TPCS8ZDB3SZCTKVH1" }




